### PR TITLE
Regression in settings page

### LINKED ISSUE #218: Regression in settings page
**Describe the bug**
When server offline, settings page does not load correctly. It returns 5xx errors

**To Reproduce**
1. 7D2D Server offline
2. Go to settings
3. Cry because there's an error

**Expected behavior**
Page loads properly

**Screenshots**

image

**Additional context**
Reported via Discord

### PR DESCRIPTION
**Pull request by niekcandaele**
Fixes #218

### CODE REVIEW

File: api/controllers/SdtdServer/settings.js [hunk 1]
```diff
@@ -48,14 +48,12 @@ module.exports = {
...
-
-    } catch (e) {
+    // Force a recheck of the CPM version in the cache
+    sails.helpers.sdtd.checkCpmVersion(server.id, true)
+      // No need to do anything
+      .then()
       // Ok to fail silently
-    }
-
+      .catch();
```
Comment (halkeye) [inline api/controllers/SdtdServer/settings.js:56]: pretty sure you can't pass in empty for then and catch we had that issue before

```suggestion
      .then(() => {}, () => {})
```

or even
```suggestion
      .then(Boolean,Boolean)
```

Does the function update server? Longer term does it make sense to be something like memupdate that runs occasionaly? Maybe even rename the function to not be check then?

Comment (niekcandaele) [reply api/controllers/SdtdServer/settings.js]: You're right ofcourse :smile: Added a test
