### PR TITLE
Fix top Discord command validation of argument

### LINKED ISSUE #349: Fix validation for top command
Reported via Discord:

image
image

Command worked when `+top deaths` was used.

Capitalization is the issue, there's already some validation but that's not working 100% 😄 .
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/master/api/hooks/discordBot/commands/sdtd/top.js#L16

For UX, it's probably best to use `.toLowercase()` on the arg

### PR DESCRIPTION
**Pull request by adhammo**
Resolves #349.

Added top command validation for arguments.

Tell me if you want to bypass capitalization of argument value and to only block argument values that aren't inside **oneOf** array irrespective of their capitalization, it is just a matter of `.toLowerCase()`.

### CODE REVIEW

**Comment by halkeye** [comment]
so does this just make it so it'll error when its not one of those values?
Personally I think includes is nicer than some
```
arg.oneOf.includes(val)
```

But I don't know anything about the discord js library so without tests will have to defer to @niekcandaele to review

**Comment by adhammo** [comment]
It will send back an error message (error property) if it's not in the **oneOf** values.

includes can replace some if you wanted the checking to be case sensitive. and if not you will be forced to write each **oneOf** value in lowercase.

File: api/hooks/discordBot/commands/sdtd/top.js [hunk 1]
```diff
@@ -13,7 +13,9 @@ class Top extends Commando.Command {
         key: 'type',
         prompt: 'Please specify which top you want to see',
         type: 'string',
-        oneOf: ['currency', 'zombies', 'players', 'deaths', 'playtime', 'score', 'level']
+        oneOf: ['currency', 'zombies', 'players', 'deaths', 'playtime', 'score', 'level'],
+        validate: (val, msg, arg) => arg.oneOf.some(valid => val === valid),
+        error: 'Top Command: Type argument value was not valid.'
```
Comment (niekcandaele) [inline api/hooks/discordBot/commands/sdtd/top.js:18]: Would it be possible to include a list of valid args here? Can reuse the `oneOf` array for this.

File: api/hooks/discordBot/commands/sdtd/top.js [hunk 2]
```diff
@@ -13,7 +13,9 @@ class Top extends Commando.Command {
         key: 'type',
```
Comment (niekcandaele) [inline api/hooks/discordBot/commands/sdtd/top.js:13]: So one thing I noticed while testing this:
image

If a user types `Deaths`, it errors out as you say. However, I think CSMM should recognize it and 'fix' the argument for the user. So a `.toLowercase()` in the validation would be nice. Make sure the actual value of the arg later in the command is also lowercased though.

Possible the [ArgumentType#parse method](https://discord.js.org/#/docs/commando/master/class/ArgumentType?scrollTo=parse) can be used for this.

**Review by niekcandaele — CHANGES_REQUESTED** [review]
Thanks for your contribution!

File: api/hooks/discordBot/commands/sdtd/top.js (hunk 1 above)
Comment (adhammo) [reply api/hooks/discordBot/commands/sdtd/top.js:18]: Are you talking about the error message? I can hardcode the valid commands or define the valid commands outside of the module exports

File: api/hooks/discordBot/commands/sdtd/top.js (hunk 2 above)
Comment (adhammo) [reply api/hooks/discordBot/commands/sdtd/top.js:13]: So, if I understand you correctly, you want commands to be case insensitive and also make the whole command lowercase for later usage?

File: api/hooks/discordBot/commands/sdtd/top.js (hunk 1 above)
Comment (niekcandaele) [reply api/hooks/discordBot/commands/sdtd/top.js:18]: I'd say define `['currency', 'zombies', 'players', 'deaths', 'playtime', 'score', 'level']` outside of the command and use it in the `oneOf` property and in the error message.

Something like 
```
error: `Top Command: Type argument value was not valid. Please use one of: ${validArgs.join(', ')}`
```

perhaps?

File: api/hooks/discordBot/commands/sdtd/top.js (hunk 2 above)
Comment (niekcandaele) [reply api/hooks/discordBot/commands/sdtd/top.js:13]: I think the best approach is to let the validation be case insenstive. (Deaths - OK, deaths - OK, deths - Not OK) and at the start of the command use `.toLowercase()` so that the command does not error when it gets to the DB sorting

**Comment by adhammo** [comment]
@niekcandaele Check the PR, please.

**Review by niekcandaele — APPROVED** [review]

**Comment by niekcandaele** [comment]
Awesome, thanks for the changes :)
