### PR TITLE
Fix customCommands that include a ; get split at places they shouldn't be

### LINKED ISSUE #468: CustomCommands that include a ; get split at places they shouldn't be
Consider the following command: `command1;command2;command3 "aaa;bbb"`

This will result in execution of
- command1
- command2
- command3 "aaa
- bbb"

This is not ideal. [The helper currently takes an array of strings](https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/master/api/helpers/sdtd/execute-custom-cmd.js#L15). I propose this is changed to allow a string to be passed in and let the helper be responsible for splitting the commands properly. This will allow handling the quoted semicolon properly.

When changing this, any current usage of that helper will need to be adjusted as well. Eg the [`split()` call here](https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/master/worker/processors/hooks/index.js#L66) should be removed and just pass the full string. CTRL+f'ing for `sails.helpers.sdtd.executeCustomCmd` should reveal all the places that need adjusting.

### PR DESCRIPTION
**Pull request by niekcandaele**
Fixes #468

### CODE REVIEW

File: api/helpers/sdtd/parse-commands-string.js [hunk 1]
```diff
@@ -30,9 +32,10 @@ module.exports = {
 
 
   fn: function (inputs, exits) {
-
-    let result = inputs.commands.split(';');
-    result = result.map(x => x.trim());
+    let result = split(inputs.commands, { separator: ';', quotes: ['"'] });
+    result = result
+      .map(x => x.trim())
+      .filter(x => x !== '');
```
Comment (halkeye) [inline api/helpers/sdtd/parse-commands-string.js:38]: Not that you need to change it, but it's usually easier to write

.filter(Boolean) which will just check for truuthy value

Comment (niekcandaele) [reply api/helpers/sdtd/parse-commands-string.js:38]: Ah I forgot an empty string is falsy. I rather play safe with js :D
