### PR TITLE
Let server owner know when discord notifications fail

### LINKED ISSUE #345: Discord notification errors are not being trapped
send() is a promise, but its not being awaited, so the catch never fires

Sentry Issue: [CSMM-WB](https://sentry.io/organizations/csmm/issues/1790183893/?referrer=github_integration)

```
DiscordAPIError: Missing Permissions
  File "/usr/src/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js", line 85, in item.request.gen.end
    new DiscordAPIError(res.request.path, res.body, res.request.method) : err);
  File "/usr/src/app/node_modules/snekfetch/src/index.js", line 215, in then
    (err) => cb ? cb(err, err.status ? err : null) : Promise.reject(err)
  File "internal/process/next_tick.js", line 68, in process._tickCallback
```

### PR DESCRIPTION
**Pull request by halkeye**
includes #344 (because i needed to update cron's as well)

Fixes #345

* Await for the discord message to finish sending
* On error, fetch the user and the discordId and try to message it

Does it make more sense to report somewhere with server id/instance/discord name?

Maybe something a bit more clear?

```
There was an error sending a CSMM notification to your channel: Error: AHH

Not sure what CSMM is? Or need some help? Join <invite link>
```

### CODE REVIEW

File: api/hooks/discordNotifications/DiscordNotification.js [hunk 1]
```diff
@@ -24,9 +29,18 @@ class DiscordNotification {
...
       if (discordChannel) {
-        discordChannel.send(embedToSend);
+        await discordChannel.send(embedToSend);
       }
     } catch (error) {
+      try {
+        const owner = await User.findOne(enrichedOptions.server.owner);
+        if (owner.discordId) {
+          const discordUser = await this.getDiscordUser(owner.discordId);
+          discordUser.send(`There was an error sending a CSMM notification to your channel: ${error}`);
```
Comment (niekcandaele) [inline api/hooks/discordNotifications/DiscordNotification.js:39]: Needs an `await` here, right?


This might get pretty spammy for users. Could be good, cause that'll force them to fix the issue. Could be bad, cause they might just get rid of CSMM.

Perhaps we can do something similar to logging hook failures?
- Set a field in redis (or DB) that a failure has occurred
- Display it in the front end with some additional info (eg: check permissions?)

**Review by niekcandaele — APPROVED** [review]

File: api/hooks/discordNotifications/DiscordNotification.js (hunk 1 above)
Comment (niekcandaele) [reply api/hooks/discordNotifications/DiscordNotification.js:39]: Eh fat fingered the approve button :p

Comment (halkeye) [reply api/hooks/discordNotifications/DiscordNotification.js:39]: > Needs an `await` here, right?

yea

> This might get pretty spammy for users. Could be good, cause that'll force them to fix the issue. Could be bad, cause they might just get rid of CSMM.

Could only do it on the first issue and let them know that discord notifications for this job is now disabled and disable it? I was trying to find the flag? I'm also not super concerned if they decide to get rid of csmm are you?

> Perhaps we can do something similar to logging hook failures?

Was thinking it might be worth having an inbox (notifications(serverId, type, message) table) where we can shove things like "your server's been disabled due to too many timeouts"

Comment (niekcandaele) [reply api/hooks/discordNotifications/DiscordNotification.js]: > I'm also not super concerned if they decide to get rid of csmm are you?
Not really, but better UX is always good :)

> Was thinking it might be worth having an inbox (notifications(serverId, type, message) table) where we can shove things like "your server's been disabled due to too many timeouts"

Yep indeed, having a solid system for this would be good! Gives us a good way to surface errors to users and will likely help debugging issues. Depending on a users privacy settings, sending a DM on Discord will not always work either

**Review by niekcandaele — APPROVED** [review]
